# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a42e03655f068de68873be151422bed30c0f7666991150b1add93f61ab9218583044ea23cb595acb8bdc851372142f495a838cdecbd913a1b805d0de35e4334

test:
  secret_key_base: bfa484dcf33b7824a387ae13ad72e52f765b08752e936fbaa13cbe20ebcd31ac73c4b1a588825212416f558fabde27db954d5b2a2b6e74e22ff6924d4c8b38c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
